### ISSUE TITLE
Spike: JetBrains Toolbox Architecture open questions

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/jetbrains-coder#425]
While exploring the new Toolbox architecture, several questions and friction points have surfaced. We should gain clarity on the below:

- [ ] JetBrains should fix the token link used to grab the dashboard token as this is showing in the URL twice
- [ ] Investigate offline support - is this possible in Toolbox?
- [ ] Support cross-user workspaces (admin logging into a user's workspace, mainly).  Should use the new wildcard host functionality. #531 
- [x] In the main environment list there is an empty view container that JetBrains should cleanup (or possibly we can fix this on our end but we need their input)
- [ ] **Nice-to-have** We should consider adding telemetry so that we can see what IDEs users are using as well as DAU. Right now, all IDE tracking is lumped into one JetBrains bucket (might not make sense to split them up since there is little technical difference). @stirby to poke into the priority of this item.
- [ ]  **Nice-to-have** It would be nice to understand how Toolbox performs compared to the existing Gateway. JetBrains has not released any performance benchmarking. We should see if a plugin is available within JetBrains to do some benchmarking of our own.

**Comment by Kira-Pilot** [comment]
Asked JetBrains about the above, waiting to hear back.

**Comment by matifali** [comment]
@f0ssel do we still have these confusions?

**Comment by code-asher** [comment]
As far as open questions, my understanding is:

- We still need to see if there is a way to do offline support (and add to our docs, since we have docs for that with Gateway)
- The double link issue may have been fixed but we just need to check the latest Toolbox build.
- I think we are not going to do any telemetry or performance benchmarking right now.

**Comment by matifali** [comment]
We are tracking all JetBrains Toolbox plugin issues in https://github.com/coder/coder-jetbrains-toolbox repo.
